
version: '3.6'
services:

   jupyter:
      build:    _docker/
      image:    triple-a:jupyter
      command:  start-notebook.sh --NotebookApp.token=''
      ports:
         - 8888:8888  # Jupyter
      volumes:
         - ./notebooks:/home/jovyan
